pr:
  autoCancel: true

stages:
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/test_deploy_pypi') }}:
  - stage: Deploy
    jobs:
    - job: testpypi
      pool:
        vmImage: 'Ubuntu-latest'
      container: python:3.8
      steps:
      - script: |
          python setup.py sdist bdist_wheel
          python -m pip install --user --upgrade twine
          python -m twine upload -r testpypi dist/*
        env:
          TWINE_USERNAME: $(TWINE_TEST_USERNAME)
          TWINE_PASSWORD: $(TWINE_TEST_PASSWORD)
        displayName: 'Push to Python Package Index'
